obj-y	:= 	board956x.o extra.o ../common/init-956x.o		\
		../common/956x.o ../common/tap-956x.o			\
		../common/ath_serial.o ../common/qca-mach-common.o	\
		flash.o ../common/ath_flash.o				\
		../common/athrs17_phy.o					\
		../common/qca-eth-956x.o
